export interface EquipmentStore {
  id: string;
  name: string;
  state: string;
  district: string;
  city: string;
  address: string;
  distance: string;
  phone: string;
  whatsapp?: string;
  rating: number;
  reviewsCount: number;
  brands: string[];
  categories: string[];
  subsidyApproved: boolean; // e.g. SMAM / DBT Subsidy Approved Dealer
  featuredProducts: {
    name: string;
    category: string;
    price: string;
    hp?: string;
    specs: string;
    subsidyEligible: boolean;
    inStock: boolean;
  }[];
}

export interface RentalListing {
  id: string;
  equipmentTitle: string;
  equipmentType: 
    | 'Small Tractor'
    | 'Tractor (Medium/Heavy)'
    | 'Power Tiller'
    | 'Rotavator'
    | 'Combine Harvester'
    | 'Seed Drill / Super Seeder'
    | 'Drone Sprayer'
    | 'Water Pump & Pipes'
    | 'Laser Land Leveler'
    | 'Thresher / Straw Reaper'
    | 'Cultivator & Harrow';
  model: string;
  hp?: string;
  ownerName: string;
  ownerType: 'Farmer' | 'Custom Hiring Centre (CHC)';
  phone: string;
  rate: number;
  rateUnit: 'hour' | 'day' | 'acre' | 'month';
  state: string;
  district: string;
  villageOrLocation: string;
  distance: string;
  driverIncluded: boolean;
  availability: string;
  notes?: string;
  verified: boolean;
  listedAt: string;
  isUserListing?: boolean;
}

export const VERIFIED_EQUIPMENT_STORES: EquipmentStore[] = [
  // =========================================================================
  // --- UTTARAKHAND ---
  // =========================================================================
  {
    id: 'uk-store-1',
    name: 'Mahindra Krishi Samarth Tractors & Mini Machinery',
    state: 'Uttarakhand',
    district: 'Dehradun',
    city: 'Dehradun',
    address: 'NH-72 Saharanpur Road, Near Transport Nagar & Mandi Gate, Dehradun',
    distance: '3.8 km',
    phone: '+919897123456',
    whatsapp: '+919897123456',
    rating: 4.8,
    reviewsCount: 142,
    brands: ['Mahindra', 'Swaraj', 'Shaktiman'],
    categories: ['Small Tractor', 'Tractor (Medium/Heavy)', 'Power Tiller', 'Rotavator'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Mahindra Yuvraj 215 NXT (15 HP Mini Tractor)',
        category: 'Small Tractor',
        price: '₹3,15,000',
        hp: '15 HP',
        specs: 'Single cylinder water-cooled engine, compact 4ft width ideal for apple & sugarcane orchards',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'Mahindra OJA 2127 4WD Mini Tractor',
        category: 'Small Tractor',
        price: '₹4,95,000',
        hp: '27 HP 4WD',
        specs: 'Japanese Yanmar engine tech, 4x4 drive, hill terrace specialized automation',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'Shaktiman Regular Light Rotavator (5 Ft)',
        category: 'Rotavator',
        price: '₹88,000',
        hp: '20-35 HP',
        specs: 'Boron steel blades, oil-bath side gear drive, suitable for compact tractors',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },
  {
    id: 'uk-store-2',
    name: 'Swaraj Tractors & Agro Machinery Center',
    state: 'Uttarakhand',
    district: 'Haridwar',
    city: 'Roorkee',
    address: 'Delhi-Haridwar Highway Bypass, Roorkee, Haridwar',
    distance: '6.4 km',
    phone: '+919897234567',
    whatsapp: '+919897234567',
    rating: 4.7,
    reviewsCount: 98,
    brands: ['Swaraj', 'Captain', 'Fieldking'],
    categories: ['Small Tractor', 'Tractor (Medium/Heavy)', 'Seed Drill / Super Seeder'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Swaraj Target 625 Mini Tractor (25 HP)',
        category: 'Small Tractor',
        price: '₹3,85,000',
        hp: '25 HP',
        specs: 'Narrow track width, dual PTO speed, synchromesh transmission, spray optimized',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'Swaraj 724 XM Orchard Special',
        category: 'Small Tractor',
        price: '₹4,30,000',
        hp: '25-30 HP',
        specs: 'Low height chassis, heavy rear lift (1000 kg), power steering',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },
  {
    id: 'uk-store-3',
    name: 'VST Shakti Power Tillers & Mini Tractors Store',
    state: 'Uttarakhand',
    district: 'Nainital',
    city: 'Haldwani',
    address: 'Nainital Bareilly Road, Near Krishi Upaj Mandi, Haldwani',
    distance: '2.5 km',
    phone: '+919897345678',
    whatsapp: '+919897345678',
    rating: 4.9,
    reviewsCount: 165,
    brands: ['VST Shakti', 'Mitsubishi', 'Honda'],
    categories: ['Small Tractor', 'Power Tiller', 'Drone Sprayer'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'VST MT 180D JAI 4WD Mini Tractor',
        category: 'Small Tractor',
        price: '₹3,25,000',
        hp: '18.5 HP 4WD',
        specs: 'All-wheel 4x4 drive, 3-cylinder diesel engine, high ground clearance for hills',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'VST Shakti 130 DI Power Tiller (13 HP)',
        category: 'Power Tiller',
        price: '₹1,85,000',
        hp: '13 HP',
        specs: 'Hand-guided multi-speed tiller, rotary blades, tilling depth up to 8 inches',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },
  {
    id: 'uk-store-4',
    name: 'Kisan Agro Engineering & Harvester Agency',
    state: 'Uttarakhand',
    district: 'Udham Singh Nagar',
    city: 'Rudrapur',
    address: 'Kashi-Bareilly Road, Industrial Area, Rudrapur',
    distance: '4.1 km',
    phone: '+919897456789',
    whatsapp: '+919897456789',
    rating: 4.6,
    reviewsCount: 84,
    brands: ['Sonalika', 'Kubota', 'Preet'],
    categories: ['Small Tractor', 'Combine Harvester', 'Rotavator'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Sonalika GT 20 Compact Tractor',
        category: 'Small Tractor',
        price: '₹3,30,000',
        hp: '20 HP',
        specs: '3 cylinder engine, multi-speed PTO, metallic hood, oil immersed brakes',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'Kubota B2441 Neostar 4WD',
        category: 'Small Tractor',
        price: '₹5,40,000',
        hp: '24 HP 4WD',
        specs: 'Japanese Super Draft Control, power steering, wet disc brakes',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },

  // =========================================================================
  // --- MAHARASHTRA ---
  // =========================================================================
  {
    id: 'mh-store-1',
    name: 'Kisan Machinery & Tractor Hub Pune',
    state: 'Maharashtra',
    district: 'Pune',
    city: 'Pune',
    address: 'Pune-Nashik Highway, Narayangaon Bypass & Hadapsar Market Yard, Pune',
    distance: '4.5 km',
    phone: '+919822123456',
    whatsapp: '+919822123456',
    rating: 4.9,
    reviewsCount: 205,
    brands: ['Mahindra', 'Kubota', 'Shaktiman'],
    categories: ['Small Tractor', 'Tractor (Medium/Heavy)', 'Rotavator', 'Drone Sprayer'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Kubota Neostar A211N-OP (Narrow Track Mini Tractor)',
        category: 'Small Tractor',
        price: '₹4,65,000',
        hp: '21 HP 4WD',
        specs: 'Specialized 2.98 ft narrow width for grape and pomegranate vineyards',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'Mahindra JIVO 245 DI 4WD Mini Tractor',
        category: 'Small Tractor',
        price: '₹4,15,000',
        hp: '24 HP 4WD',
        specs: '86 Nm peak torque, 2-speed PTO, multi-crop inter-culture specialist',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'Shaktiman Champion Rotavator (6 Ft)',
        category: 'Rotavator',
        price: '₹1,02,000',
        hp: '40-55 HP',
        specs: 'Multi-speed gearbox, depth skid shoes, heavy duty tynes',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },
  {
    id: 'mh-store-2',
    name: 'Sahyadri Agro Equipments & Vineyard Solutions',
    state: 'Maharashtra',
    district: 'Nashik',
    city: 'Nashik',
    address: 'Mumbai-Agra National Highway, Dwarka Circle & Pimpalgaon Mandi, Nashik',
    distance: '3.1 km',
    phone: '+919822234567',
    whatsapp: '+919822234567',
    rating: 4.7,
    reviewsCount: 130,
    brands: ['VST Shakti', 'Swaraj', 'Mitra Sprayers'],
    categories: ['Small Tractor', 'Power Tiller', 'Drone Sprayer'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Mitra Airotec Vineyard Air-Blast Sprayer (600L)',
        category: 'Drone Sprayer',
        price: '₹2,65,000',
        hp: '24+ HP PTO',
        specs: 'Italian brass nozzles, rear turbofan, covers 5 acres in 1 hour',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'Swaraj Target 630 4WD Orchard Tractor',
        category: 'Small Tractor',
        price: '₹5,10,000',
        hp: '29 HP 4WD',
        specs: 'Category 1 hitch, 980 kg lift, dual clutch, mechanical shuttle',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },
  {
    id: 'mh-store-3',
    name: 'Mahalaxmi Agro Machinery & Sugarcane Implements',
    state: 'Maharashtra',
    district: 'Kolhapur',
    city: 'Kolhapur',
    address: 'Shiroli MIDC, Near Kolhapur Sugar Mandi, Kolhapur',
    distance: '4.2 km',
    phone: '+919822345678',
    whatsapp: '+919822345678',
    rating: 4.8,
    reviewsCount: 118,
    brands: ['John Deere', 'Captain', 'Fieldking'],
    categories: ['Small Tractor', 'Tractor (Medium/Heavy)', 'Rotavator'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Captain 283 4WD Sugarcane Special',
        category: 'Small Tractor',
        price: '₹3,90,000',
        hp: '28 HP 4WD',
        specs: 'High ground clearance, narrow track for sugarcane ratoon management',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'Fieldking Heavy Disc Harrow (14 Discs)',
        category: 'Rotavator',
        price: '₹62,000',
        hp: '35+ HP',
        specs: 'Notched high-carbon boron steel discs with sealed bearing hubs',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },
  {
    id: 'mh-store-4',
    name: 'Vidarbha Farm Machinery & Cotton Equipment Centre',
    state: 'Maharashtra',
    district: 'Nagpur',
    city: 'Nagpur',
    address: 'Amravati Road, Wadi, Near APMC Kalamna, Nagpur',
    distance: '5.6 km',
    phone: '+919822456789',
    whatsapp: '+919822456789',
    rating: 4.6,
    reviewsCount: 95,
    brands: ['Mahindra', 'Sonalika', 'Aspee'],
    categories: ['Small Tractor', 'Drone Sprayer', 'Water Pump & Pipes'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Sonalika DI 30 Baagban Super Mini',
        category: 'Small Tractor',
        price: '₹4,25,000',
        hp: '30 HP',
        specs: 'Heavy duty front axle, side-shift gear lever, 1000 kg lift capacity',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'Aspee HTP Tractor-Mounted Boom Sprayer (400L)',
        category: 'Drone Sprayer',
        price: '₹75,000',
        hp: '20+ HP',
        specs: 'Triplex plunger pump, 16 brass nozzles with stainless steel boom',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },

  // =========================================================================
  // --- PUNJAB ---
  // =========================================================================
  {
    id: 'pb-store-1',
    name: 'Punjab Tractors & Farm Machinery Showroom',
    state: 'Punjab',
    district: 'Ludhiana',
    city: 'Ludhiana',
    address: 'GT Road, Near Asia Biggest Grain Market, Khanna, Ludhiana',
    distance: '1.9 km',
    phone: '+919814123456',
    whatsapp: '+919814123456',
    rating: 4.9,
    reviewsCount: 220,
    brands: ['John Deere', 'Swaraj', 'Mahindra'],
    categories: ['Small Tractor', 'Tractor (Medium/Heavy)', 'Seed Drill / Super Seeder'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'John Deere 3028EN Orchard Tractor',
        category: 'Small Tractor',
        price: '₹5,65,000',
        hp: '28 HP',
        specs: 'Narrow width design, high back-up torque, factory-fitted synchromesh transmission',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'Punjab Super Seeder (7 Ft 11 Tynes)',
        category: 'Seed Drill / Super Seeder',
        price: '₹2,35,000',
        hp: '45+ HP',
        specs: 'Stubble management combined with direct wheat seeding, SMAM 50% subsidy certified',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },
  {
    id: 'pb-store-2',
    name: 'Malwa Agro Equipments & Drone Center',
    state: 'Punjab',
    district: 'Bathinda',
    city: 'Bathinda',
    address: 'Mansa Road, Industrial Estate, Bathinda',
    distance: '5.0 km',
    phone: '+919814234567',
    whatsapp: '+919814234567',
    rating: 4.8,
    reviewsCount: 112,
    brands: ['Sonalika', 'Fieldking', 'IoTechWorld'],
    categories: ['Small Tractor', 'Drone Sprayer', 'Rotavator'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Sonalika Tiger DI 26 4WD Mini Tractor',
        category: 'Small Tractor',
        price: '₹4,45,000',
        hp: '26 HP 4WD',
        specs: 'Mitsubishi 3-cylinder engine, hydro-static steering, 750 kg lift',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'Agri Drone 10L Hexacopter Sprayer',
        category: 'Drone Sprayer',
        price: '₹4,20,000',
        hp: 'Battery',
        specs: 'Sprays 1 acre in 7 minutes, obstacle avoidance sensors, DGCA type certified',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },
  {
    id: 'pb-store-3',
    name: 'Doaba Harvesters & Agricultural Implements Hub',
    state: 'Punjab',
    district: 'Jalandhar',
    city: 'Jalandhar',
    address: 'Near Rama Mandi Bypass & APMC Yard, Jalandhar',
    distance: '3.7 km',
    phone: '+919814345678',
    whatsapp: '+919814345678',
    rating: 4.7,
    reviewsCount: 104,
    brands: ['Preet', 'Standard', 'Kubota'],
    categories: ['Combine Harvester', 'Small Tractor', 'Rotavator'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Preet 987 Self-Propelled Combine Harvester',
        category: 'Combine Harvester',
        price: '₹22,50,000',
        hp: '101 HP',
        specs: 'Heavy duty Straw Management System (SMS), hydraulic unload, grain tank 2.5 ton',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },

  // =========================================================================
  // --- HARYANA ---
  // =========================================================================
  {
    id: 'hr-store-1',
    name: 'Karnal Tractor & Implement Mega Bazaar',
    state: 'Haryana',
    district: 'Karnal',
    city: 'Karnal',
    address: 'Indri Road, Near New Grain Market APMC, Karnal',
    distance: '3.2 km',
    phone: '+919812123456',
    whatsapp: '+919812123456',
    rating: 4.8,
    reviewsCount: 180,
    brands: ['Mahindra', 'Captain', 'Eicher'],
    categories: ['Small Tractor', 'Tractor (Medium/Heavy)', 'Rotavator'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Captain 200 DI 4WD Mini Tractor',
        category: 'Small Tractor',
        price: '₹3,40,000',
        hp: '20 HP 4WD',
        specs: 'Single cylinder 895 cc diesel, heavy drawbar pull, 9 forward speeds',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'Eicher 188 4WD Orchard Compact',
        category: 'Small Tractor',
        price: '₹3,20,000',
        hp: '18 HP 4WD',
        specs: 'Air-cooled robust engine, side-shift gears, low fuel consumption (1.2 L/hr)',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },
  {
    id: 'hr-store-2',
    name: 'Hisar Agro Implements & Laser Leveler Showroom',
    state: 'Haryana',
    district: 'Hisar',
    city: 'Hisar',
    address: 'Delhi Bypass Road, Near Agroha Mor, Hisar',
    distance: '4.8 km',
    phone: '+919812234567',
    whatsapp: '+919812234567',
    rating: 4.7,
    reviewsCount: 89,
    brands: ['Landforce', 'Shaktiman', 'Farmtrac'],
    categories: ['Laser Land Leveler', 'Small Tractor', 'Rotavator'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Landforce Automatic Laser Land Leveler (7 Ft)',
        category: 'Laser Land Leveler',
        price: '₹3,10,000',
        hp: '50+ HP',
        specs: 'Dual slope digital transmitter, Trimble compatible laser receiver, saves 35% irrigation',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },

  // =========================================================================
  // --- UTTAR PRADESH ---
  // =========================================================================
  {
    id: 'up-store-1',
    name: 'Braj Bhoomi Tractors & Agricultural Agency',
    state: 'Uttar Pradesh',
    district: 'Agra',
    city: 'Agra',
    address: 'Transport Nagar, Delhi-Agra Highway, Agra',
    distance: '3.9 km',
    phone: '+919839123456',
    whatsapp: '+919839123456',
    rating: 4.8,
    reviewsCount: 190,
    brands: ['Mahindra', 'Sonalika', 'Shaktiman'],
    categories: ['Small Tractor', 'Tractor (Medium/Heavy)', 'Rotavator'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Mahindra Yuvraj 215 NXT Mini Tractor',
        category: 'Small Tractor',
        price: '₹3,10,000',
        hp: '15 HP',
        specs: 'Single cylinder diesel engine, adjustable track width, potato inter-culture ready',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'Potato Digger / Harvester (Single Row)',
        category: 'Rotavator',
        price: '₹75,000',
        hp: '20-35 HP',
        specs: 'Vibrating sieve mechanism, extracts whole potatoes without skin damage',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },
  {
    id: 'up-store-2',
    name: 'Awadh Kisan Machinery & Tractor Hub Lucknow',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    city: 'Lucknow',
    address: 'Faizabad Road, Chinhat & Dubagga Mandi Bypass, Lucknow',
    distance: '3.5 km',
    phone: '+919839234567',
    whatsapp: '+919839234567',
    rating: 4.9,
    reviewsCount: 215,
    brands: ['Kubota', 'Mahindra', 'Shaktiman', 'Captain'],
    categories: ['Small Tractor', 'Power Tiller', 'Drone Sprayer', 'Rotavator'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Kubota Neostar B2741S 4WD Mini Tractor',
        category: 'Small Tractor',
        price: '₹5,70,000',
        hp: '27 HP 4WD',
        specs: '3-cylinder E-TVCS diesel engine, 9F+3R transmission, ideal for mango orchards & vegetable cultivation',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'Shaktiman Semi-Champion Rotavator (5.5 Ft)',
        category: 'Rotavator',
        price: '₹95,000',
        hp: '30-45 HP',
        specs: 'Dual speed gearbox with L-type boron blades for deep puddle preparation',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },
  {
    id: 'up-store-3',
    name: 'Western UP Tractor & Implement Junction Meerut',
    state: 'Uttar Pradesh',
    district: 'Meerut',
    city: 'Meerut',
    address: 'Delhi-Roorkee Bypass, Near Partapur Flyover, Meerut',
    distance: '4.7 km',
    phone: '+919839345678',
    whatsapp: '+919839345678',
    rating: 4.7,
    reviewsCount: 145,
    brands: ['Sonalika', 'Escorts Farmtrac', 'Fieldking'],
    categories: ['Small Tractor', 'Tractor (Medium/Heavy)', 'Seed Drill / Super Seeder'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Farmtrac Atom 26 Mini Tractor',
        category: 'Small Tractor',
        price: '₹4,80,000',
        hp: '26 HP 4WD',
        specs: 'Heavy 4-wheel drive, constant mesh gearbox, compact turning radius',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },
  {
    id: 'up-store-4',
    name: 'Purvanchal Agro Equipment & Solar Pump Store Varanasi',
    state: 'Uttar Pradesh',
    district: 'Varanasi',
    city: 'Varanasi',
    address: 'GT Road, Rohaniya & Raja Talab Mandi, Varanasi',
    distance: '5.2 km',
    phone: '+919839456789',
    whatsapp: '+919839456789',
    rating: 4.8,
    reviewsCount: 132,
    brands: ['VST Shakti', 'Tata Solar', 'Captain'],
    categories: ['Power Tiller', 'Water Pump & Pipes', 'Small Tractor'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: '5 HP Solar Submersible Borewell Pump (PM-KUSUM)',
        category: 'Water Pump & Pipes',
        price: '₹1,95,000',
        hp: '5 HP',
        specs: 'C.R.I. stainless steel pump with 5 kW solar array, up to 70% state subsidy',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },

  // =========================================================================
  // --- MADHYA PRADESH ---
  // =========================================================================
  {
    id: 'mp-store-1',
    name: 'Malwa Krishi Yantra & Tractor Store Indore',
    state: 'Madhya Pradesh',
    district: 'Indore',
    city: 'Indore',
    address: 'Nemawar Road, Near Palda Industrial Area & Laxmi Bai Mandi, Indore',
    distance: '3.6 km',
    phone: '+919826123456',
    whatsapp: '+919826123456',
    rating: 4.9,
    reviewsCount: 230,
    brands: ['John Deere', 'Mahindra', 'Shaktiman'],
    categories: ['Small Tractor', 'Tractor (Medium/Heavy)', 'Rotavator', 'Seed Drill / Super Seeder'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Mahindra OJA 2121 4WD Mini Tractor',
        category: 'Small Tractor',
        price: '₹4,40,000',
        hp: '21 HP 4WD',
        specs: 'Compact track width, IoT enabled GPS fleet management, auto-depth hydraulics',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'Soybean Automatic Seed Drill & Fertilizer Box (9 Tynes)',
        category: 'Seed Drill / Super Seeder',
        price: '₹55,000',
        hp: '25-40 HP',
        specs: 'Fluted roller metering mechanism, prevents soybean seed rupture during sowing',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },
  {
    id: 'mp-store-2',
    name: 'Narmada Valley Agro Machinery Bhopal',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    city: 'Bhopal',
    address: 'Hoshangabad Road, Near Karond Krishi Upaj Mandi, Bhopal',
    distance: '4.3 km',
    phone: '+919826234567',
    whatsapp: '+919826234567',
    rating: 4.7,
    reviewsCount: 115,
    brands: ['Eicher', 'Swaraj', 'Captain'],
    categories: ['Small Tractor', 'Tractor (Medium/Heavy)', 'Power Tiller'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Eicher 242 NC Compact Tractor',
        category: 'Small Tractor',
        price: '₹3,70,000',
        hp: '25 HP',
        specs: 'Legendary 1-cylinder air-cooled diesel engine, lowest fuel running cost in India',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },

  // =========================================================================
  // --- RAJASTHAN ---
  // =========================================================================
  {
    id: 'rj-store-1',
    name: 'Jaipur Krishi Yantra & Solar Farm Machinery',
    state: 'Rajasthan',
    district: 'Jaipur',
    city: 'Jaipur',
    address: 'Sikar Road, Near Harmada Agro Mandi & VKI Area, Jaipur',
    distance: '4.6 km',
    phone: '+919829123456',
    whatsapp: '+919829123456',
    rating: 4.7,
    reviewsCount: 125,
    brands: ['Mahindra', 'Captain', 'Tata Solar'],
    categories: ['Small Tractor', 'Water Pump & Pipes', 'Rotavator'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Captain 280 DI 4WD Mini Tractor',
        category: 'Small Tractor',
        price: '₹3,75,000',
        hp: '28 HP 4WD',
        specs: '2 cylinder 1290 cc engine, hydrostatic power steering, 1000 kg lift',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: '5 HP Solar Submersible Agriculture Pump (PM-KUSUM)',
        category: 'Water Pump & Pipes',
        price: '₹1,85,000',
        hp: '5 HP',
        specs: 'Stainless steel borewell pump, 4.8 kW solar panels, 60-80% subsidy certified',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },
  {
    id: 'rj-store-2',
    name: 'Hadoti Agro Implements & Harvester Agency Kota',
    state: 'Rajasthan',
    district: 'Kota',
    city: 'Kota',
    address: 'Jhalawar Road, Near Bhamashah Krishi Upaj Mandi, Kota',
    distance: '3.9 km',
    phone: '+919829234567',
    whatsapp: '+919829234567',
    rating: 4.8,
    reviewsCount: 96,
    brands: ['Sonalika', 'New Holland', 'Fieldking'],
    categories: ['Combine Harvester', 'Small Tractor', 'Seed Drill / Super Seeder'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'New Holland 3037 TX Mini Tractor',
        category: 'Small Tractor',
        price: '₹5,35,000',
        hp: '39 HP Compact',
        specs: 'High lift capacity (1500 kg), oil-immersed disc brakes, dual-acting power steering',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },

  // =========================================================================
  // --- GUJARAT ---
  // =========================================================================
  {
    id: 'gj-store-1',
    name: 'Gujarat Krishi Sadhan & Captain Mini Tractors Ahmedabad',
    state: 'Gujarat',
    district: 'Ahmedabad',
    city: 'Ahmedabad',
    address: 'Sanand-Sarkhej Highway, Near APMC Market Yard, Ahmedabad',
    distance: '5.1 km',
    phone: '+919825123456',
    whatsapp: '+919825123456',
    rating: 4.9,
    reviewsCount: 188,
    brands: ['Captain', 'Mahindra', 'Shaktiman'],
    categories: ['Small Tractor', 'Rotavator', 'Drone Sprayer'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Captain 250 DI 4WD Mini Tractor',
        category: 'Small Tractor',
        price: '₹3,60,000',
        hp: '25 HP 4WD',
        specs: 'Heavy front axle, 9+3 transmission, specifically crafted for cotton & groundnut inter-row weeding',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'Shaktiman Drip-Line Retractor & Rotary Weeder',
        category: 'Rotavator',
        price: '₹48,000',
        hp: '15-25 HP',
        specs: 'Weeds between rows without cutting drip laterals in horticulture',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },
  {
    id: 'gj-store-2',
    name: 'Saurashtra Diesel Engines & Agri Implements Rajkot',
    state: 'Gujarat',
    district: 'Rajkot',
    city: 'Rajkot',
    address: 'Aji GIDC Industrial Area, Near Bedi Mandi Yard, Rajkot',
    distance: '3.4 km',
    phone: '+919825234567',
    whatsapp: '+919825234567',
    rating: 4.8,
    reviewsCount: 160,
    brands: ['Fieldking', 'Captain', 'Kirloskar'],
    categories: ['Small Tractor', 'Water Pump & Pipes', 'Rotavator'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Captain 120 DI 15 HP Mini Tractor',
        category: 'Small Tractor',
        price: '₹2,95,000',
        hp: '15 HP',
        specs: 'Single cylinder diesel engine, low turning radius, economical choice for small landholders',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },

  // =========================================================================
  // --- KARNATAKA ---
  // =========================================================================
  {
    id: 'ka-store-1',
    name: 'Namma Krishi Tractors & VST Mini Machinery Bengaluru',
    state: 'Karnataka',
    district: 'Bangalore Urban',
    city: 'Bengaluru',
    address: 'Tumkur Road, Near Yeshwantpur APMC Mandi, Bengaluru',
    distance: '2.8 km',
    phone: '+919845123456',
    whatsapp: '+919845123456',
    rating: 4.8,
    reviewsCount: 175,
    brands: ['VST Shakti', 'Mahindra', 'Kubota'],
    categories: ['Small Tractor', 'Power Tiller', 'Water Pump & Pipes'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'VST 929 DI 4WD Mini Tractor (28 HP)',
        category: 'Small Tractor',
        price: '₹4,75,000',
        hp: '28 HP 4WD',
        specs: 'Aerodynamic bonnet, 3-cylinder diesel, 750 kg hydraulic capacity',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'VST Shakti 9 HP Power Weeder & Cultivator',
        category: 'Power Tiller',
        price: '₹85,000',
        hp: '9 HP',
        specs: 'Lightweight petrol/diesel engine, easy turning, ideal for horticulture weeding',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },
  {
    id: 'ka-store-2',
    name: 'Cauvery Agro Equipments & Power Tillers Mysuru',
    state: 'Karnataka',
    district: 'Mysuru',
    city: 'Mysuru',
    address: 'Bannur Road, Near APMC Bandipalya, Mysuru',
    distance: '4.0 km',
    phone: '+919845234567',
    whatsapp: '+919845234567',
    rating: 4.7,
    reviewsCount: 92,
    brands: ['Kubota', 'VST Shakti', 'Honda'],
    categories: ['Power Tiller', 'Small Tractor', 'Water Pump & Pipes'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Kubota PEM140DI 14 HP Power Tiller',
        category: 'Power Tiller',
        price: '₹1,90,000',
        hp: '14 HP',
        specs: 'Direct injection diesel, balanced rotary tilling depth control',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },

  // =========================================================================
  // --- BIHAR ---
  // =========================================================================
  {
    id: 'br-store-1',
    name: 'Patna Agro Machinery & Power Tiller Center',
    state: 'Bihar',
    district: 'Patna',
    city: 'Patna',
    address: 'Bailey Road, Saguna More, Danapur & Meena Bazar Mandi, Patna',
    distance: '4.8 km',
    phone: '+919835123456',
    whatsapp: '+919835123456',
    rating: 4.6,
    reviewsCount: 110,
    brands: ['VST Shakti', 'Sonalika', 'Kirloskar'],
    categories: ['Small Tractor', 'Power Tiller', 'Water Pump & Pipes'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Sonalika GT 22 4WD Mini Tractor',
        category: 'Small Tractor',
        price: '₹3,55,000',
        hp: '22 HP 4WD',
        specs: '3-cylinder water-cooled engine, 8 forward + 2 reverse gears, 650 kg lift',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'Kirloskar 15 HP Power Tiller',
        category: 'Power Tiller',
        price: '₹1,95,000',
        hp: '15 HP',
        specs: 'Self-start diesel engine, dual PTO, works in wet paddy muddy fields',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },
  {
    id: 'br-store-2',
    name: 'Tirhut Kisan Implements & Borewell Pump Store Muzaffarpur',
    state: 'Bihar',
    district: 'Muzaffarpur',
    city: 'Muzaffarpur',
    address: 'Rewa Road, Bhagwanpur Chowk & APMC Yard, Muzaffarpur',
    distance: '3.8 km',
    phone: '+919835234567',
    whatsapp: '+919835234567',
    rating: 4.7,
    reviewsCount: 88,
    brands: ['Mahindra', 'Captain', 'Shaktiman'],
    categories: ['Small Tractor', 'Rotavator', 'Water Pump & Pipes'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Mahindra Yuvraj 215 Mini Tractor',
        category: 'Small Tractor',
        price: '₹3,12,000',
        hp: '15 HP',
        specs: 'Compact 15 HP tractor with low fuel consumption for vegetable and litchi orchards',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },

  // =========================================================================
  // --- WEST BENGAL ---
  // =========================================================================
  {
    id: 'wb-store-1',
    name: 'Rice Bowl Farm Machinery & Power Tillers Burdwan',
    state: 'West Bengal',
    district: 'Purba Bardhaman',
    city: 'Burdwan',
    address: 'Grand Trunk Road, Near Alisha Bus Stand & APMC Rice Mandi, Burdwan',
    distance: '3.5 km',
    phone: '+919832123456',
    whatsapp: '+919832123456',
    rating: 4.8,
    reviewsCount: 140,
    brands: ['VST Shakti', 'Kamco', 'Kubota'],
    categories: ['Power Tiller', 'Small Tractor', 'Water Pump & Pipes'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Kamco Super DI Power Tiller (12 HP)',
        category: 'Power Tiller',
        price: '₹1,75,000',
        hp: '12 HP',
        specs: 'Kerala Agro Machinery Corporation design, high clearance for wet paddy puddling',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'Kubota B2441 Neostar 4WD Mini Tractor',
        category: 'Small Tractor',
        price: '₹5,35,000',
        hp: '24 HP 4WD',
        specs: 'High tractive power in wet clay soils, 9 speed transmission',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },

  // =========================================================================
  // --- TELANGANA & ANDHRA PRADESH ---
  // =========================================================================
  {
    id: 'ts-store-1',
    name: 'Deccan Agri Machinery & Drone Center Hyderabad',
    state: 'Telangana',
    district: 'Hyderabad',
    city: 'Hyderabad',
    address: 'Kukatpally & Medchal Highway, Near Bowenpally Agriculture Market, Hyderabad',
    distance: '5.4 km',
    phone: '+919849123456',
    whatsapp: '+919849123456',
    rating: 4.8,
    reviewsCount: 165,
    brands: ['Mahindra', 'IoTechWorld', 'VST Shakti'],
    categories: ['Small Tractor', 'Drone Sprayer', 'Power Tiller'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Drishti 16L Agriculture Drone Sprayer',
        category: 'Drone Sprayer',
        price: '₹4,90,000',
        hp: 'Electric Battery',
        specs: 'Dual RTK positioning, terrain following radar, 10 min per acre high flow nozzle',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },
  {
    id: 'ap-store-1',
    name: 'Krishna Delta Farm Machinery & Harvesters Vijayawada',
    state: 'Andhra Pradesh',
    district: 'Krishna',
    city: 'Vijayawada',
    address: 'Gollapudi Bypass, Near APMC Market Yard, Vijayawada',
    distance: '4.1 km',
    phone: '+919848123456',
    whatsapp: '+919848123456',
    rating: 4.7,
    reviewsCount: 135,
    brands: ['Kubota', 'Yanmar', 'Shaktiman'],
    categories: ['Combine Harvester', 'Small Tractor', 'Rotavator'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Kubota DC-68G-HK Paddy Combine Harvester',
        category: 'Combine Harvester',
        price: '₹24,50,000',
        hp: '68 HP',
        specs: 'Crawler rubber tracks for wet flooded paddy fields, 2-meter cutter bar',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },

  // =========================================================================
  // --- TAMIL NADU ---
  // =========================================================================
  {
    id: 'tn-store-1',
    name: 'Kongu Agri Machinery & Mini Tractor Center Coimbatore',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    city: 'Coimbatore',
    address: 'Mettupalayam Road, Near Thudiyalur & Annur Agri Market, Coimbatore',
    distance: '3.8 km',
    phone: '+919842123456',
    whatsapp: '+919842123456',
    rating: 4.9,
    reviewsCount: 185,
    brands: ['VST Shakti', 'Captain', 'Yanmar'],
    categories: ['Small Tractor', 'Power Tiller', 'Water Pump & Pipes'],
    subsidyApproved: true,
    featuredProducts: [
      {
        name: 'Captain 200 DI Mini Tractor',
        category: 'Small Tractor',
        price: '₹3,45,000',
        hp: '20 HP 4WD',
        specs: 'Ideal for coconut grove tilling, turmeric bed planting, and drip operations',
        subsidyEligible: true,
        inStock: true,
      },
      {
        name: 'Texmo 5 HP Agriculture Openwell Submersible Pump',
        category: 'Water Pump & Pipes',
        price: '₹38,000',
        hp: '5 HP',
        specs: 'Copper wound motor, high water discharge 600 LPM, energy efficient 5-star',
        subsidyEligible: true,
        inStock: true,
      },
    ],
  },
];

export const INITIAL_RENTAL_LISTINGS: RentalListing[] = [
  // --- UTTARAKHAND RENTALS ---
  {
    id: 'rent-uk-1',
    equipmentTitle: 'Mahindra Yuvraj 215 Mini Tractor',
    equipmentType: 'Small Tractor',
    model: 'Yuvraj 215 NXT (15 HP)',
    hp: '15 HP',
    ownerName: 'Harish Rawat (Farmer)',
    ownerType: 'Farmer',
    phone: '+919897112233',
    rate: 350,
    rateUnit: 'hour',
    state: 'Uttarakhand',
    district: 'Dehradun',
    villageOrLocation: 'Sahaspur, Vikas Nagar, Dehradun',
    distance: '5.2 km',
    driverIncluded: true,
    availability: 'Available Today',
    notes: 'Comes with 3-tyne cultivator and small trolley. Excellent for hill terrace plowing.',
    verified: true,
    listedAt: 'Today',
  },
  {
    id: 'rent-uk-2',
    equipmentTitle: 'Shaktiman 5ft Rotavator',
    equipmentType: 'Rotavator',
    model: 'Shaktiman Regular Light 5ft',
    hp: '20-40 HP compatible',
    ownerName: 'Virendra Singh Negi',
    ownerType: 'Farmer',
    phone: '+919897223344',
    rate: 700,
    rateUnit: 'day',
    state: 'Uttarakhand',
    district: 'Haridwar',
    villageOrLocation: 'Bahadrabad, Haridwar',
    distance: '7.8 km',
    driverIncluded: false,
    availability: 'Available from Tomorrow',
    notes: 'Brand new blades, smooth oil-sealed drive. Can attach to any tractor.',
    verified: true,
    listedAt: 'Yesterday',
  },
  {
    id: 'rent-uk-3',
    equipmentTitle: 'VST 13 HP Power Tiller with Rotary Blades',
    equipmentType: 'Power Tiller',
    model: 'VST Shakti 130 DI',
    hp: '13 HP',
    ownerName: 'Ganga Ram Joshi',
    ownerType: 'Farmer',
    phone: '+919897334455',
    rate: 650,
    rateUnit: 'day',
    state: 'Uttarakhand',
    district: 'Nainital',
    villageOrLocation: 'Kaladhungi, Haldwani',
    distance: '6.1 km',
    driverIncluded: true,
    availability: 'Available This Week',
    notes: 'Tiller operator included in rate. Best for orchards and vegetable nursery bed preparation.',
    verified: true,
    listedAt: '2 days ago',
  },
  {
    id: 'rent-uk-4',
    equipmentTitle: 'Swaraj 744 FE 48 HP Tractor + Trolley',
    equipmentType: 'Tractor (Medium/Heavy)',
    model: 'Swaraj 744 FE (48 HP)',
    hp: '48 HP',
    ownerName: 'Kashipur Farmers Custom Hiring Centre',
    ownerType: 'Custom Hiring Centre (CHC)',
    phone: '+919897445566',
    rate: 600,
    rateUnit: 'hour',
    state: 'Uttarakhand',
    district: 'Udham Singh Nagar',
    villageOrLocation: 'Mandi Samiti Yard, Kashipur',
    distance: '3.4 km',
    driverIncluded: true,
    availability: 'Available Today',
    notes: 'Government CHC rates. Heavy hydraulic trolley, MB plow, and disc harrow available.',
    verified: true,
    listedAt: 'Today',
  },

  // --- MAHARASHTRA RENTALS ---
  {
    id: 'rent-mh-1',
    equipmentTitle: 'Kubota Neostar B2441 (4WD Mini Tractor)',
    equipmentType: 'Small Tractor',
    model: 'Kubota Neostar 24 HP',
    hp: '24 HP',
    ownerName: 'Suresh Patil (Farmer)',
    ownerType: 'Farmer',
    phone: '+919822112233',
    rate: 400,
    rateUnit: 'hour',
    state: 'Maharashtra',
    district: 'Nashik',
    villageOrLocation: 'Pimpalgaon Baswant, Nashik',
    distance: '3.6 km',
    driverIncluded: true,
    availability: 'Available Today',
    notes: 'Ideal for grape canopy spraying and sugarcane inter-row rotavation.',
    verified: true,
    listedAt: 'Today',
  },
  {
    id: 'rent-mh-2',
    equipmentTitle: 'Laser Land Leveler with Transmitter',
    equipmentType: 'Laser Land Leveler',
    model: 'Spectra Precision Laser Leveler (7ft)',
    hp: '50+ HP required',
    ownerName: 'Narayangaon Farmer Cooperative',
    ownerType: 'Custom Hiring Centre (CHC)',
    phone: '+919822223344',
    rate: 900,
    rateUnit: 'acre',
    state: 'Maharashtra',
    district: 'Pune',
    villageOrLocation: 'Junnar, Pune',
    distance: '7.1 km',
    driverIncluded: true,
    availability: 'Available Tomorrow',
    notes: 'Saves 30% irrigation water and improves crop germination uniformity.',
    verified: true,
    listedAt: 'Yesterday',
  },
  {
    id: 'rent-mh-3',
    equipmentTitle: 'Mahindra JIVO 225 DI (20 HP Compact)',
    equipmentType: 'Small Tractor',
    model: 'Mahindra JIVO 225',
    hp: '20 HP',
    ownerName: 'Santosh Jadhav (Farmer)',
    ownerType: 'Farmer',
    phone: '+919822334455',
    rate: 380,
    rateUnit: 'hour',
    state: 'Maharashtra',
    district: 'Pune',
    villageOrLocation: 'Baramati, Pune',
    distance: '5.9 km',
    driverIncluded: true,
    availability: 'Available Today',
    notes: 'Equipped with 3ft orchard rotavator and seed drill.',
    verified: true,
    listedAt: 'Today',
  },

  // --- PUNJAB RENTALS ---
  {
    id: 'rent-pb-1',
    equipmentTitle: 'John Deere 5050D (50 HP) + Super Seeder',
    equipmentType: 'Seed Drill / Super Seeder',
    model: 'John Deere 5050D with 7ft Super Seeder',
    hp: '50 HP',
    ownerName: 'Gurpreet Singh Dhillon',
    ownerType: 'Farmer',
    phone: '+919814112233',
    rate: 1100,
    rateUnit: 'acre',
    state: 'Punjab',
    district: 'Ludhiana',
    villageOrLocation: 'Samrala Road, Khanna',
    distance: '4.2 km',
    driverIncluded: true,
    availability: 'Available Today',
    notes: 'Zero stubble burning direct wheat sowing. Precision depth control included.',
    verified: true,
    listedAt: 'Today',
  },
  {
    id: 'rent-pb-2',
    equipmentTitle: 'Paddy & Wheat Combine Harvester with SMS',
    equipmentType: 'Combine Harvester',
    model: 'Preet 987 Track Harvester',
    hp: '101 HP',
    ownerName: 'Amritsar Cooperative CHC Hub',
    ownerType: 'Custom Hiring Centre (CHC)',
    phone: '+919814223344',
    rate: 1400,
    rateUnit: 'acre',
    state: 'Punjab',
    district: 'Amritsar',
    villageOrLocation: 'Rayya, Amritsar',
    distance: '8.5 km',
    driverIncluded: true,
    availability: 'Advance Booking Open',
    notes: 'Fitted with Straw Management System (SMS). Clean grain cutting with zero wastage.',
    verified: true,
    listedAt: 'Yesterday',
  },

  // --- HARYANA RENTALS ---
  {
    id: 'rent-hr-1',
    equipmentTitle: 'Captain 200 DI Mini Tractor',
    equipmentType: 'Small Tractor',
    model: 'Captain 200 DI (20 HP 4WD)',
    hp: '20 HP',
    ownerName: 'Rameshwar Sharma (Farmer)',
    ownerType: 'Farmer',
    phone: '+919812112233',
    rate: 380,
    rateUnit: 'hour',
    state: 'Haryana',
    district: 'Karnal',
    villageOrLocation: 'Gharaunda, Karnal',
    distance: '5.8 km',
    driverIncluded: true,
    availability: 'Available Today',
    notes: 'Small 4WD tractor for vegetable intercultural spraying and ridge making.',
    verified: true,
    listedAt: 'Today',
  },

  // --- UTTAR PRADESH RENTALS ---
  {
    id: 'rent-up-1',
    equipmentTitle: 'Mahindra 275 DI TU (39 HP Tractor + Cultivator)',
    equipmentType: 'Tractor (Medium/Heavy)',
    model: 'Mahindra 275 DI TU',
    hp: '39 HP',
    ownerName: 'Ram Sevak Yadav (Farmer)',
    ownerType: 'Farmer',
    phone: '+919839112233',
    rate: 450,
    rateUnit: 'hour',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    villageOrLocation: 'Mohanlalganj, Lucknow',
    distance: '6.3 km',
    driverIncluded: true,
    availability: 'Available Today',
    notes: 'Includes 9-tyne cultivator and 2-bottom MB plough. Diesel included.',
    verified: true,
    listedAt: 'Today',
  },
  {
    id: 'rent-up-2',
    equipmentTitle: 'Drone Sprayer 10 Litre for Paddy & Wheat',
    equipmentType: 'Drone Sprayer',
    model: 'Kisan Drone 10L',
    hp: 'Electric Battery',
    ownerName: 'Kisan Seva CHC Agro Hub',
    ownerType: 'Custom Hiring Centre (CHC)',
    phone: '+919839223344',
    rate: 350,
    rateUnit: 'acre',
    state: 'Uttar Pradesh',
    district: 'Agra',
    villageOrLocation: 'Fatehabad, Agra',
    distance: '8.1 km',
    driverIncluded: true,
    availability: 'Available Tomorrow',
    notes: 'Certified pilot included. High speed precision spraying covers 15 acres per day.',
    verified: true,
    listedAt: 'Yesterday',
  },

  // --- MADHYA PRADESH RENTALS ---
  {
    id: 'rent-mp-1',
    equipmentTitle: 'Swaraj 735 FE Tractor + 6ft Rotavator',
    equipmentType: 'Tractor (Medium/Heavy)',
    model: 'Swaraj 735 FE (40 HP)',
    hp: '40 HP',
    ownerName: 'Kailash Patidar (Farmer)',
    ownerType: 'Farmer',
    phone: '+919826112233',
    rate: 550,
    rateUnit: 'hour',
    state: 'Madhya Pradesh',
    district: 'Indore',
    villageOrLocation: 'Mhow, Indore',
    distance: '4.8 km',
    driverIncluded: true,
    availability: 'Available Today',
    notes: 'Experienced tractor driver included. Fine tilth bed preparation for wheat and garlic.',
    verified: true,
    listedAt: 'Today',
  },

  // --- RAJASTHAN RENTALS ---
  {
    id: 'rent-rj-1',
    equipmentTitle: 'Multicrop Thresher (Wheat, Mustard, Gram)',
    equipmentType: 'Thresher / Straw Reaper',
    model: 'Tokai Super Multicrop Thresher',
    hp: '35 HP compatible',
    ownerName: 'Mukesh Choudhary (Farmer)',
    ownerType: 'Farmer',
    phone: '+919829112233',
    rate: 450,
    rateUnit: 'hour',
    state: 'Rajasthan',
    district: 'Jaipur',
    villageOrLocation: 'Chomu, Jaipur',
    distance: '8.2 km',
    driverIncluded: true,
    availability: 'Available Today',
    notes: 'High capacity grain separation with minimal seed breakage.',
    verified: true,
    listedAt: 'Today',
  },

  // --- KARNATAKA RENTALS ---
  {
    id: 'rent-ka-1',
    equipmentTitle: 'VST Shakti 929 DI 4WD Mini Tractor',
    equipmentType: 'Small Tractor',
    model: 'VST 929 DI (28 HP)',
    hp: '28 HP',
    ownerName: 'Manjunath Gowda',
    ownerType: 'Farmer',
    phone: '+919845112233',
    rate: 420,
    rateUnit: 'hour',
    state: 'Karnataka',
    district: 'Bangalore Urban',
    villageOrLocation: 'Nelamangala, Bengaluru',
    distance: '6.4 km',
    driverIncluded: true,
    availability: 'Available Today',
    notes: 'Fitted with 4ft rotavator and post-hole digger for arecanut plantations.',
    verified: true,
    listedAt: 'Today',
  },
];
